input {  
  beats {  
    port => 5044  
  }  
}  
  
output {  
  elasticsearch {  
    hosts => ["http://elasticsearch:9200"]  
    user => "elastic"  
    password => "changeme" # Same password as set in docker-compose.yml  
    index => "logstash-%{+YYYY.MM.dd}"  
  }  
}  