image:  
  repository: krranjan/hello-world-app  
  tag: hello-world-app  
  pullPolicy: IfNotPresent  

service:  
  type: ClusterIP  
  port: 5000  

ingress:  
  enabled: false  
serviceAccount:  
  create: true    
autoscaling:  
  enabled: true  
  minReplicas: 1  
  maxReplicas: 5  
  cpuUtilizationPercentage: 50    
