{{- if .Values.serviceAccount.create | default true }}  
apiVersion: v1  
kind: ServiceAccount  
metadata:  
    name: {{ .Release.Name }}  
        namespace: {{ .Release.Namespace }}  
          {{- end }}  
